version: "3.9"

networks:
  micro_net:
    driver: bridge

services:

  # ---------------------------------------------------------------------------
  # INFRASTRUCTURE (Databases, Message Brokers, Cache)
  # ---------------------------------------------------------------------------

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    networks:
      - micro_net

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - micro_net

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - micro_net

  auth_db:
    image: postgres:14
    container_name: auth_db
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - micro_net

  user_db:
    image: postgres:14
    container_name: user_db
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - micro_net

  chat_db:
    image: postgres:14
    container_name: chat_db
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - chat_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - micro_net

  chat_service:
    build: ./chat_services
    container_name: chat_service
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_NAME=chatdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=chat_db
      - POSTGRES_PORT=5432
    ports:
      - "8002:8002"
    depends_on:
      - redis
      - chat_db
    networks:
      - micro_net

  auth_service:
    build: ./auth_services
    container_name: auth_service
    env_file:
      - ./auth_services/.env
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: admin
      RABBITMQ_VHOST: /
      RABBITMQ_QUEUE: user_events
      POSTGRES_HOST: auth_db
    ports:
      - "8000:8000"
    depends_on:
      - auth_db
      - rabbitmq
    networks:
      - micro_net

  user_service:
    build:
      context: ./user_services/user_service
      dockerfile: Dockerfile
    container_name: user_service
    env_file:
      - ./user_services/.env
    environment:
      DJANGO_SETTINGS_MODULE: user_service.settings
      PORT: 8001
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: admin
      RABBITMQ_VHOST: /
      RABBITMQ_QUEUE: user_events
      POSTGRES_HOST: user_db
    volumes:
      - ./user_services/user_service:/app
    ports:
      - "8001:8001"
    depends_on:
      - user_db
      - rabbitmq
      - auth_service
    networks:
      - micro_net

  ai_service:
    build: 
      context: ./ai_services/ai_service
      dockerfile: Dockerfile
    container_name: ai_service
    ports:
      - "8003:8003"
    volumes:
      # PERSISTENCE FOR CHROMA DB (files)
      # Mount the host 'vector_store' directory to container path
      - ./ai_services/ai_service/vector_store:/app/vector_store
    networks:
      - micro_net


  # ---------------------------------------------------------------------------
  # WORKERS
  # ---------------------------------------------------------------------------

  auth_celery_worker:
    build: ./auth_services
    container_name: auth_celery_worker
    working_dir: /app/auth_service
    command: celery -A src.infrastructure.celery worker -l info
    env_file:
      - ./auth_services/.env
    environment:
      - DJANGO_SETTINGS_MODULE=src.main.settings
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=auth_db
    depends_on:
      - auth_db
      - rabbitmq
      - redis
    networks:
      - micro_net

  auth_celery_beat:
    build: ./auth_services
    container_name: auth_celery_beat
    working_dir: /app/auth_service
    command: celery -A src.infrastructure.celery beat -l info
    env_file:
      - ./auth_services/.env
    environment:
      - DJANGO_SETTINGS_MODULE=src.main.settings
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=auth_db
    depends_on:
      - auth_db
      - rabbitmq
      - redis
    networks:
      - micro_net

volumes:
  auth_db_data:
  user_db_data:
  chat_db_data:
